name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t mlops-flask .

    - name: Push the Docker image to GitHub Packages
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && docker tag mlops-flask:latest ghcr.io/bluebird6/mlops-flask/mlops-flask:latest && docker push ghcr.io/bluebird6/mlops-flask/mlops-flask:latest

